version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.5.0-browsers
    working_directory: ~/cv
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "package.json" }}
      - run:
          name: Install project dependencies
          command: yarn install
      - save_cache:
          key: dep-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build project
          command: yarn build
      - persist_to_workspace:
          root: ~/cv
          paths:
            - .git/
            - .circleci/
            - package.json
            - dist/
  deploy:
    docker:
      - image: circleci/node:9.2.0-browsers
    working_directory: ~/cv
    steps:
      - add-ssh-keys:
          fingerprints:
            - "4e:cf:57:09:d4:79:0a:da:5e:61:a5:fc:97:bc:42:8e"
      - run:
          name: Update Git config
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
      - attach_workspace:
          at: ~/cv
      - deploy:
          name: Deploy project
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            echo tyom.semonov.com > dist/CNAME
            mv ~/cv/.circleci/ ~/cv/dist/

            npm i gh-pages
            yarn deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
