version: 2

jobs:
  check-build:
    docker:
      - image: circleci/node:10.17.0-browsers
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "package.json" }}
      - run:
          name: Install project dependencies
          command: yarn install
      - save_cache:
          key: dep-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint source
          command: yarn lint
      - run:
          name: CodeChecks
          command: |
            yarn export
            yarn codechecks
  deploy:
    docker:
      - image: circleci/node:10.17.0-browsers
    working_directory: ~/app
    steps:
      - add-ssh-keys:
          fingerprints:
            - "4e:cf:57:09:d4:79:0a:da:5e:61:a5:fc:97:bc:42:8e"
      - checkout
      - restore_cache:
          key: dep-cache-{{ checksum "package.json" }}  -
      - run:
          name: Install project dependencies
          command: yarn install
      - run:
          name: Build app and Storybook as static sites
          command: yarn prepare-deploy
      - run:
          name: Update Git config
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
      - attach_workspace:
          at: ~/app
      - deploy:
          name: Deploy project
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            echo tyom.semonov.com > dist/CNAME
            echo "Keep CircleCI happy: avoid warnings and attempts to build."
            mv ~/app/.circleci/ ~/app/dist/

            yarn deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - check-build:
          filters:
            branches:
              ignore:
                - master
                - gh-pages
      - deploy:
          filters:
            branches:
              only: master
