name: Builder
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint source
        run: yarn lint

      - name: Build app and generate PDF
        run: yarn export

      - name: Deploy to Now
        run: |
          DEPLOYMENT_URL=$(npx now -t ${NOW_TOKEN} __sapper__/export/ --name tyom-cv-commit)
          echo "::set-env name=DEPLOYMENT_URL::$DEPLOYMENT_URL"
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}

      - name: CodeChecks
        run: |
          npx wait-on $DEPLOYMENT_URL
          npx envsub codechecks.yml
          npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
